CC=g++
INC=/usr/local/include
LIB=-L /usr/local/lib -L /usr/lib/x86_64-linux-gnu -L/usr/lib64
LIBS=-lGLEW -lglfw3 -lX11 -lXxf86vm -lpthread -lGL -lXrandr -lXi 

all:
	$(CC) main.cpp $(LIB) $(LIBS) -o hello


